global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: hesapbilir-live
    static_configs:
    - targets:
      - 'uygulama.hesapbilir.com'
  - job_name: prometheus
    static_configs:
    - targets:
      - 'prometheus:9090'
  